### ISSUE TITLE
Add rubocop as a dependency in gemspec

### ISSUE THREAD

**Issue by samarthkathal** [DmitryTsepelev/rubocop_director#14]
gem name `rubocop_director` and its use cases themselves implies that Rubocop will be required to use this gem.

Should we add Rubocop as a dependency for this gem and update the readme?

**Comment by DmitryTsepelev** [comment]
Hey @samarthkathal! What if rubocop is installed globally? dependency means that we need _code_ to use this gem, but we're not calling rubocop classes anywhere, right?

**Comment by samarthkathal** [comment]
Right. Then adding it as a dependency will not be the right way.
