### ISSUE TITLE
GenerateConfig should show a prompt when config already exists

### ISSUE THREAD

**Issue by DmitryTsepelev** [DmitryTsepelev/rubocop_director#2]

**Comment by samarthkathal** [comment]
Hi @DmitryTsepelev, Correct me if I am wrong but this looks like a good first-timer issue. I'd be happy to pick this up.

**Comment by DmitryTsepelev** [comment]
Indeed! Just need to add one puts, one gets and one condition 🙂

**Comment by samarthkathal** [comment]
Thanks! Do you have a sample prompt in mind? If not, I think maybe a simple `.rubocop-director.yml already exists` should be sufficient.
